// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwvgsgrwfpbnurdjsuer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3dmdzZ3J3ZnBibnVyZGpzdWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0MTYzMzYsImV4cCI6MjA1Njk5MjMzNn0.yZ1DlQGO5Ygd0w9AthC8lFLQhuXIbyGFG4pMhaps7l0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);